const countries = {
  아시아: {
    아프가니스탄: "afghanistan",
    아르메니아: "armenia",
    아제르바이잔: "azerbaijan",
    바레인: "bahrain",
    방글라데시: "bangladesh",
    부탄: "bhutan",
    브루나이: "brunei",
    캄보디아: "cambodia",
    중국: "china",
    사이프러스: "cyprus",
    조지아: "georgia",
    인도: "india",
    인도네시아: "indonesia",
    이란: "iran",
    이라크: "iraq",
    이스라엘: "israel",
    일본: "japan",
    요르단: "jordan",
    카자흐스탄: "kazakhstan",
    쿠웨이트: "kuwait",
    키르기스스탄: "kyrgyzstan",
    라오스: "laos",
    레바논: "lebanon",
    말레이시아: "malaysia",
    몰디브: "maldives",
    몽골: "mongolia",
    미얀마: "myanmar",
    네팔: "nepal",
    북한: "north-korea",
    오만: "oman",
    파키스탄: "pakistan",
    필리핀: "philippines",
    카타르: "qatar",
    러시아: "russia",
    사우디아라비아: "saudi-arabia",
    싱가포르: "singapore",
    대한민국: "south-korea",
    스리랑카: "sri-lanka",
    시리아: "syria",
    타이완: "taiwan",
    타지키스탄: "tajikistan",
    태국: "thailand",
    동티모르: "timor-leste",
    터키: "turkey",
    투르크메니스탄: "turkmenistan",
    아랍에미리트: "united-arab-emirates",
    우즈베키스탄: "uzbekistan",
    베트남: "vietnam",
    예멘: "yemen",
  },
  오세아니아: {
    오스트레일리아: "australia",
    뉴질랜드: "new-zealand",
    파푸아뉴기니: "papua-new-guinea",
    피지: "fiji",
    "솔로몬 제도": "solomon-islands",
    바누아투: "vanuatu",
    사모아: "samoa",
    키리바시: "kiribati",
    통가: "tonga",
    "미크로네시아 연방": "micronesia",
    팔라우: "palau",
    나우루: "nauru",
    투발루: "tuvalu",
    "마셜 제도": "marshall-islands",
  },
  아프리카: {
    알제리: "algeria",
    앙골라: "angola",
    베냉: "benin",
    보츠와나: "botswana",
    부르키나파소: "burkina-faso",
    부룬디: "burundi",
    카보베르데: "cape-verde",
    카메룬: "cameroon",
    "중앙아프리카 공화국": "central-african-republic",
    차드: "chad",
    코모로: "comoros",
    "콩고 공화국": "republic-of-the-congo",
    "콩고 민주 공화국": "democratic-republic-of-the-congo",
    지부티: "djibouti",
    이집트: "egypt",
    "적도 기니": "equatorial-guinea",
    에리트레아: "eritrea",
    에스와티니: "eswatini",
    에티오피아: "ethiopia",
    가봉: "gabon",
    감비아: "gambia",
    가나: "ghana",
    기니: "guinea",
    기니비사우: "guinea-bissau",
    케냐: "kenya",
    레소토: "lesotho",
    라이베리아: "liberia",
    리비아: "libya",
    마다가스카르: "madagascar",
    말라위: "malawi",
    말리: "mali",
    모리타니: "mauritania",
    모리셔스: "mauritius",
    모로코: "morocco",
    모잠비크: "mozambique",
    나미비아: "namibia",
    니제르: "niger",
    나이지리아: "nigeria",
    르완다: "rwanda",
    "상투메 프린시페": "sao-tome-and-principe",
    세네갈: "senegal",
    세이셸: "seychelles",
    시에라리온: "sierra-leone",
    소말리아: "somalia",
    "남아프리카 공화국": "south-africa",
    남수단: "south-sudan",
    수단: "sudan",
    탄자니아: "tanzania",
    토고: "togo",
    튀니지: "tunisia",
    우간다: "uganda",
    잠비아: "zambia",
    짐바브웨: "zimbabwe",
  },
  유럽: {
    알바니아: "albania",
    안도라: "andorra",
    아르메니아: "armenia",
    오스트리아: "austria",
    아제르바이잔: "azerbaijan",
    벨라루스: "belarus",
    벨기에: "belgium",
    "보스니아 헤르체고비나": "bosnia-and-herzegovina",
    불가리아: "bulgaria",
    크로아티아: "croatia",
    키프로스: "cyprus",
    체코: "czech-republic",
    덴마크: "denmark",
    에스토니아: "estonia",
    핀란드: "finland",
    프랑스: "france",
    조지아: "georgia",
    독일: "germany",
    그리스: "greece",
    헝가리: "hungary",
    아이슬란드: "iceland",
    아일랜드: "ireland",
    이탈리아: "italy",
    라트비아: "latvia",
    리히텐슈타인: "liechtenstein",
    리투아니아: "lithuania",
    룩셈부르크: "luxembourg",
    몰타: "malta",
    몰도바: "moldova",
    모나코: "monaco",
    몬테네그로: "montenegro",
    네덜란드: "netherlands",
    북마케도니아: "north-macedonia",
    노르웨이: "norway",
    폴란드: "poland",
    포르투갈: "portugal",
    루마니아: "romania",
    러시아: "russia",
    산마리노: "san-marino",
    세르비아: "serbia",
    슬로바키아: "slovakia",
    슬로베니아: "slovenia",
    스페인: "spain",
    스웨덴: "sweden",
    스위스: "switzerland",
    터키: "turkey",
    우크라이나: "ukraine",
    영국: "united-kingdom",
    "바티칸 시국": "vatican-city",
  },
  북아메리카: {
    "앤티가 바부다": "antigua-and-barbuda",
    바하마: "bahamas",
    바베이도스: "barbados",
    벨리즈: "belize",
    캐나다: "canada",
    코스타리카: "costa-rica",
    쿠바: "cuba",
    도미니카: "dominica",
    "도미니카 공화국": "dominican-republic",
    엘살바도르: "el-salvador",
    그레나다: "grenada",
    과테말라: "guatemala",
    아이티: "haiti",
    온두라스: "honduras",
    자메이카: "jamaica",
    멕시코: "mexico",
    니카라과: "nicaragua",
    파나마: "panama",
    "세인트키츠 네비스": "saint-kitts-and-nevis",
    세인트루시아: "saint-lucia",
    "세인트빈센트 그레나딘": "saint-vincent-and-the-grenadines",
    "트리니다드 토바고": "trinidad-and-tobago",
    미국: "united-states",
  },
  남아메리카: {
    아르헨티나: "argentina",
    볼리비아: "bolivia",
    브라질: "brazil",
    칠레: "chile",
    콜롬비아: "colombia",
    에콰도르: "ecuador",
    가이아나: "guyana",
    파라과이: "paraguay",
    페루: "peru",
    수리남: "suriname",
    우루과이: "uruguay",
    베네수엘라: "venezuela",
  },
};

export default countries;
