const travelCountries = {
    "afghanistan": "아프가니스탄",
    "armenia": "아르메니아",
    "azerbaijan": "아제르바이잔",
    "bahrain": "바레인",
    "bangladesh": "방글라데시",
    "bhutan": "부탄",
    "brunei": "브루나이",
    "cambodia": "캄보디아",
    "china": "중국",
    "cyprus": "사이프러스",
    "georgia": "조지아",
    "india": "인도",
    "indonesia": "인도네시아",
    "iran": "이란",
    "iraq": "이라크",
    "israel": "이스라엘",
    "japan": "일본",
    "jordan": "요르단",
    "kazakhstan": "카자흐스탄",
    "kuwait": "쿠웨이트",
    "kyrgyzstan": "키르기스스탄",
    "laos": "라오스",
    "lebanon": "레바논",
    "malaysia": "말레이시아",
    "maldives": "몰디브",
    "mongolia": "몽골",
    "myanmar": "미얀마",
    "nepal": "네팔",
    "north-korea": "북한",
    "oman": "오만",
    "pakistan": "파키스탄",
    "philippines": "필리핀",
    "qatar": "카타르",
    "russia": "러시아",
    "saudi-arabia": "사우디아라비아",
    "singapore": "싱가포르",
    "south-korea": "대한민국",
    "sri-lanka": "스리랑카",
    "syria": "시리아",
    "taiwan": "타이완",
    "tajikistan": "타지키스탄",
    "thailand": "태국",
    "timor-leste": "동티모르",
    "turkey": "터키",
    "turkmenistan": "투르크메니스탄",
    "united-arab-emirates": "아랍에미리트",
    "uzbekistan": "우즈베키스탄",
    "vietnam": "베트남",
    "yemen": "예멘",
    "australia": "오스트레일리아",
    "new-zealand": "뉴질랜드",
    "papua-new-guinea": "파푸아뉴기니",
    "fiji": "피지",
    "solomon-islands": "솔로몬 제도",
    "vanuatu": "바누아투",
    "samoa": "사모아",
    "kiribati": "키리바시",
    "tonga": "통가",
    "micronesia": "미크로네시아 연방",
    "palau": "팔라우",
    "nauru": "나우루",
    "tuvalu": "투발루",
    "marshall-islands": "마셜 제도",
    "algeria": "알제리",
    "angola": "앙골라",
    "benin": "베냉",
    "botswana": "보츠와나",
    "burkina-faso": "부르키나파소",
    "burundi": "부룬디",
    "cape-verde": "카보베르데",
    "cameroon": "카메룬",
    "central-african-republic": "중앙아프리카 공화국",
    "chad": "차드",
    "comoros": "코모로",
    "republic-of-the-congo": "콩고 공화국",
    "democratic-republic-of-the-congo": "콩고 민주 공화국",
    "djibouti": "지부티",
    "egypt": "이집트",
    "equatorial-guinea": "적도 기니",
    "eritrea": "에리트레아",
    "eswatini": "에스와티니",
    "ethiopia": "에티오피아",
    "gabon": "가봉",
    "gambia": "감비아",
    "ghana": "가나",
    "guinea": "기니",
    "guinea-bissau": "기니비사우",
    "kenya": "케냐",
    "lesotho": "레소토",
    "liberia": "라이베리아",
    "libya": "리비아",
    "madagascar": "마다가스카르",
    "malawi": "말라위",
    "mali": "말리",
    "mauritania": "모리타니",
    "mauritius": "모리셔스",
    "morocco": "모로코",
    "mozambique": "모잠비크",
    "namibia": "나미비아",
    "niger": "니제르",
    "nigeria": "나이지리아",
    "rwanda": "르완다",
    "sao-tome-and-principe": "상투메 프린시페",
    "senegal": "세네갈",
    "seychelles": "세이셸",
    "sierra-leone": "시에라리온",
    "somalia": "소말리아",
    "south-africa": "남아프리카 공화국",
    "south-sudan": "남수단",
    "sudan": "수단",
    "tanzania": "탄자니아",
    "togo": "토고",
    "tunisia": "튀니지",
    "uganda": "우간다",
    "zambia": "잠비아",
    "zimbabwe": "짐바브웨",
    "albania": "알바니아",
    "andorra": "안도라",
    "austria": "오스트리아",
    "belarus": "벨라루스",
    "belgium": "벨기에",
    "bosnia-and-herzegovina": "보스니아 헤르체고비나",
    "bulgaria": "불가리아",
    "croatia": "크로아티아",
    "czech-republic": "체코",
    "denmark": "덴마크",
    "estonia": "에스토니아",
    "finland": "핀란드",
    "france": "프랑스",
    "germany": "독일",
    "greece": "그리스",
    "hungary": "헝가리",
    "iceland": "아이슬란드",
    "ireland": "아일랜드",
    "italy": "이탈리아",
    "latvia": "라트비아",
    "liechtenstein": "리히텐슈타인",
    "lithuania": "리투아니아",
    "luxembourg": "룩셈부르크",
    "malta": "몰타",
    "moldova": "몰도바",
    "monaco": "모나코",
    "montenegro": "몬테네그로",
    "netherlands": "네덜란드",
    "north-macedonia": "북마케도니아",
    "norway": "노르웨이",
    "poland": "폴란드",
    "portugal": "포르투갈",
    "romania": "루마니아",
    "san-marino": "산마리노",
    "serbia": "세르비아",
    "slovakia": "슬로바키아",
    "slovenia": "슬로베니아",
    "spain": "스페인",
    "sweden": "스웨덴",
    "switzerland": "스위스",
    "ukraine": "우크라이나",
    "united-kingdom": "영국",
    "vatican-city": "바티칸 시국",
    "antigua-and-barbuda": "앤티가 바부다",
    "bahamas": "바하마",
    "barbados": "바베이도스",
    "belize": "벨리즈",
    "canada": "캐나다",
    "costa-rica": "코스타리카",
    "cuba": "쿠바",
    "dominica": "도미니카",
    "dominican-republic": "도미니카 공화국",
    "el-salvador": "엘살바도르",
    "grenada": "그레나다",
    "guatemala": "과테말라",
    "haiti": "아이티",
    "honduras": "온두라스",
    "jamaica": "자메이카",
    "mexico": "멕시코",
    "nicaragua": "니카라과",
    "panama": "파나마",
    "saint-kitts-and-nevis": "세인트키츠 네비스",
    "saint-lucia": "세인트루시아",
    "saint-vincent-and-the-grenadines": "세인트빈센트 그레나딘",
    "trinidad-and-tobago": "트리니다드 토바고",
    "united-states": "미국",
    "argentina": "아르헨티나",
    "bolivia": "볼리비아",
    "brazil": "브라질",
    "chile": "칠레",
    "colombia": "콜롬비아",
    "ecuador": "에콰도르",
    "guyana": "가이아나",
    "paraguay": "파라과이",
    "peru": "페루",
    "suriname": "수리남",
    "uruguay": "우루과이",
    "venezuela": "베네수엘라",
};
export default travelCountries;
