import countries from "./countries";

const travelCountries = {
  가나: "ghana",
  가봉: "gabon",
  가이아나: "guyana",
  감비아: "gambia",
  과테말라: "guatemala",
  그레나다: "grenada",
  그리스: "greece",
  기니: "guinea",
  기니비사우: "guinea-bissau",
  나미비아: "namibia",
  나우루: "nauru",
  나이지리아: "nigeria",
  "남아프리카 공화국": "south-africa",
  남수단: "south-sudan",
  네덜란드: "netherlands",
  네팔: "nepal",
  노르웨이: "norway",
  뉴질랜드: "new-zealand",
  니제르: "niger",
  니카라과: "nicaragua",
  대한민국: "south-korea",
  덴마크: "denmark",
  도미니카: "dominica",
  "도미니카 공화국": "dominican-republic",
  동티모르: "timor-leste",
  라이베리아: "liberia",
  라오스: "laos",
  라트비아: "latvia",
  러시아: "russia",
  레바논: "lebanon",
  레소토: "lesotho",
  루마니아: "romania",
  룩셈부르크: "luxembourg",
  르완다: "rwanda",
  리비아: "libya",
  리투아니아: "lithuania",
  리히텐슈타인: "liechtenstein",
  마다가스카르: "madagascar",
  "마셜 제도": "marshall-islands",
  말라위: "malawi",
  말레이시아: "malaysia",
  말리: "mali",
  멕시코: "mexico",
  모나코: "monaco",
  모로코: "morocco",
  모리셔스: "mauritius",
  모리타니: "mauritania",
  몬테네그로: "montenegro",
  몰도바: "moldova",
  몰디브: "maldives",
  몰타: "malta",
  몽골: "mongolia",
  미국: "united-states",
  미얀마: "myanmar",
  "미크로네시아 연방": "micronesia",
  바누아투: "vanuatu",
  바레인: "bahrain",
  바베이도스: "barbados",
  "바티칸 시국": "vatican-city",
  바하마: "bahamas",
  방글라데시: "bangladesh",
  베냉: "benin",
  베네수엘라: "venezuela",
  베트남: "vietnam",
  벨기에: "belgium",
  벨라루스: "belarus",
  벨리즈: "belize",
  "보스니아 헤르체고비나": "bosnia-and-herzegovina",
  보츠와나: "botswana",
  볼리비아: "bolivia",
  부르키나파소: "burkina-faso",
  부룬디: "burundi",
  북마케도니아: "north-macedonia",
  북한: "north-korea",
  불가리아: "bulgaria",
  브라질: "brazil",
  브루나이: "brunei",
  사모아: "samoa",
  사이프러스: "cyprus",
  산마리노: "san-marino",
  "상투메 프린시페": "sao-tome-and-principe",
  세네갈: "senegal",
  세르비아: "serbia",
  세인트루시아: "saint-lucia",
  "세인트빈센트 그레나딘": "saint-vincent-and-the-grenadines",
  "세인트키츠 네비스": "saint-kitts-and-nevis",
  세이셸: "seychelles",
  소말리아: "somalia",
  "솔로몬 제도": "solomon-islands",
  수단: "sudan",
  수리남: "suriname",
  스웨덴: "sweden",
  스위스: "switzerland",
  스페인: "spain",
  슬로바키아: "slovakia",
  슬로베니아: "slovenia",
  시에라리온: "sierra-leone",
  싱가포르: "singapore",
  아르메니아: "armenia",
  아르헨티나: "argentina",
  아이슬란드: "iceland",
  아이티: "haiti",
  아제르바이잔: "azerbaijan",
  아프가니스탄: "afghanistan",
  안도라: "andorra",
  알바니아: "albania",
  알제리: "algeria",
  앙골라: "angola",
  에스토니아: "estonia",
  에스와티니: "eswatini",
  에콰도르: "ecuador",
  에티오피아: "ethiopia",
  엘살바도르: "el-salvador",
  영국: "united-kingdom",
  예멘: "yemen",
  오만: "oman",
  오스트리아: "austria",
  오스트레일리아: "australia",
  온두라스: "honduras",
  요르단: "jordan",
  우간다: "uganda",
  우루과이: "uruguay",
  우즈베키스탄: "uzbekistan",
  우크라이나: "ukraine",
  이라크: "iraq",
  아일랜드: "ireland",
  이란: "iran",
  이스라엘: "israel",
  이집트: "egypt",
  이탈리아: "italy",
  인도: "india",
  인도네시아: "indonesia",
  일본: "japan",
  자메이카: "jamaica",
  잠비아: "zambia",
  "적도 기니": "equatorial-guinea",
  "중앙아프리카 공화국": "central-african-republic",
  지부티: "djibouti",
  짐바브웨: "zimbabwe",
  차드: "chad",
  체코: "czech-republic",
  칠레: "chile",
  카메룬: "cameroon",
  카보베르데: "cape-verde",
  카자흐스탄: "kazakhstan",
  카타르: "qatar",
  캄보디아: "cambodia",
  캐나다: "canada",
  케냐: "kenya",
  코모로: "comoros",
  코스타리카: "costa-rica",
  코트디부아르: "ivory-coast",
  콜롬비아: "colombia",
  "콩고 공화국": "republic-of-the-congo",
  "콩고 민주 공화국": "democratic-republic-of-the-congo",
  쿠바: "cuba",
  쿠웨이트: "kuwait",
  크로아티아: "croatia",
  키르기스스탄: "kyrgyzstan",
  키리바시: "kiribati",
  타지키스탄: "tajikistan",
  탄자니아: "tanzania",
  태국: "thailand",
  터키: "turkey",
  토고: "togo",
  통가: "tonga",
  투르크메니스탄: "turkmenistan",
  투발루: "tuvalu",
  튀니지: "tunisia",
  "트리니다드 토바고": "trinidad-and-tobago",
  파나마: "panama",
  파라과이: "paraguay",
  파푸아뉴기니: "papua-new-guinea",
  팔라우: "palau",
  페루: "peru",
  포르투갈: "portugal",
  폴란드: "poland",
  프랑스: "france",
  피지: "fiji",
  핀란드: "finland",
  필리핀: "philippines",
  헝가리: "hungary",
  호주: "australia",
  홍콩: "hong-kong",
};

export default travelCountries;
